### ISSUE TITLE
Display single pet listing

### ISSUE THREAD

**Issue by jesskuen** [cferdinandi/petfinderAPI4everybody#43]
Hi there,

Your plugin is working great for my client's Adoptable Dogs page, but I'd like to be able to display a single pet listing in the sidebar like the old PHP functions were able to do. Is that possible with this & I'm just not seeing it, or is that option no longer available within the plugin?

Thanks!

**Comment by cferdinandi** [comment]
I'm not sure which PHP functions you're referring to. I've never offered a PHP option that did that.

That said, you could use this plugin and just request a single pet listing back.

**Comment by jesskuen** [comment]
Hi, just a quick follow-up. Here's what I was talking about...
https://github.com/cferdinandi/petfinder-api-for-wordpress#individual-pets

Perhaps the "in the sidebar" was confusing -- I did that on my own -- but the other plugin -- that's what I meant by "functions," which is how it's referred to in the actual PHP file -- you built offered a single pet listing option, in addition to the full listing option. I'll just play around and figure out how to make both work with this plugin.

**Comment by cferdinandi** [comment]
Ohhh yea, that! I could probably bake something like that into the API, but, candidly, my priorities are elsewhere at the moment.

**Comment by cferdinandi** [comment]
While this continues to be a good idea, I'm unable to properly maintain this plugin or work on feature development, so I'm closing this as "won't fix."
