### ISSUE TITLE
petfinderAPI4everybody is not defined

### ISSUE THREAD

**Issue by rivkadr** [cferdinandi/petfinderAPI4everybody#45]
I'm stymied on this one - this is on localhost, so I can't show you the code, but this is basically it:

I'm including the .js file in the <HEAD>:

`<script type='text/javascript' src='http://localhost/testsite/wp-content/themes/place/assets/scripts/petfinderAPI4everybody.min.js?ver=1539801108'></script>`

And I've tried two different ways to init the code. First way:

```
jQuery(document).ready(function(){

petfinderAPI4everybody.init({
		key: 'MYAPICODEHERE', // Your API key with Petfinder
		shelterID: 'CA764', // Your Petfinder shelter ID
		templates: {
			// The layout for the page that displays all pets
			allPets:
				'<div>' +
					'<div>' +
						'<img src="{{photo.1.medium}}">' +
					'</div>' +
					'<h2>{{name}}</h2>' +
					'<p><a href="{{url.pet}}">View Full Profile</a></p>' +
					'<hr>' +
				'</div>',
			onePet: null, // The layout for individual pet profiles [optional]
			asideAllPets: null, // The layout for secondary content on the "All Pets" page [optional]
			asideOnePet: null, // The layout for secondary content on individual pet pages [optional]
		}
	});

});
```
And the second way, which was the petfinderAPI4everybody.init just down in the footer, right before the closing </BODY> tag. 

Either way I do it, I'm still getting 'petfinderAPI4everybody is not defined'. I've confirmed that the .JS file is loading and that the contents are there. Any ideas what is up?

**Comment by cferdinandi** [comment]
The global object you want to use for `init()` and all the other functions is `petfinderAPI`:

```js
petfinderAPI.init({
		key: 'MYAPICODEHERE', // Your API key with Petfinder
		shelterID: 'CA764', // Your Petfinder shelter ID
		templates: {
			// The layout for the page that displays all pets
			allPets:
				'<div>' +
					'<div>' +
						'<img src="{{photo.1.medium}}">' +
					'</div>' +
					'<h2>{{name}}</h2>' +
					'<p><a href="{{url.pet}}">View Full Profile</a></p>' +
					'<hr>' +
				'</div>',
			onePet: null, // The layout for individual pet profiles [optional]
			asideAllPets: null, // The layout for secondary content on the "All Pets" page [optional]
			asideOnePet: null, // The layout for secondary content on individual pet pages [optional]
		}
	});

});
```

**Comment by rivkadr** [comment]
You need to update your documentation on this site, then, because all I did was literally copy+paste what was on this page: https://github.com/cferdinandi/petfinderAPI4everybody

**Comment by cferdinandi** [comment]
Doh, good catch!

**Comment by cferdinandi** [comment]
Updated docs
